define( [ ], function( ) {
	
	gifs = [
		{ url: 'data/img/signs/accept.gif',         name: 'accept', 	label: 'Accept'		},
		{ url: 'data/img/signs/actor.gif',          name: 'actor', 		label: 'Actor'		},
		{ url: 'data/img/signs/against.gif',        name: 'against', 	label: 'Against'	},
		{ url: 'data/img/signs/almost.gif',        	name: 'almost', 	label: 'Almost'		},
		{ url: 'data/img/signs/american.gif',       name: 'american', 	label: 'American'	},
		{ url: 'data/img/signs/banana.gif',       	name: 'banana', 	label: 'Banana'		},
		{ url: 'data/img/signs/bat.gif',            name: 'bat',		label: 'Bat' 		},
		{ url: 'data/img/signs/bear.gif',           name: 'bear',		label: 'Bear' 		},
		{ url: 'data/img/signs/book.gif',           name: 'book',		label: 'Book' 		},
		{ url: 'data/img/signs/cant.gif',           name: 'cant',		label: "Can't" 		},
		{ url: 'data/img/signs/careless.gif',       name: 'careless',	label: 'Careless' 	},
		{ url: 'data/img/signs/cat.gif',            name: 'cat',		label: 'Cat' 		},
		{ url: 'data/img/signs/child.gif',          name: 'child',		label: 'Child' 		},
		{ url: 'data/img/signs/delicious.gif',      name: 'delicious',	label: 'Delicious'	},
		{ url: 'data/img/signs/dig.gif',      		name: 'dig',		label: 'Dig'		},
		{ url: 'data/img/signs/dinosaur.gif',      	name: 'dinosaur',	label: 'Dinosaur'	},
		{ url: 'data/img/signs/doctor.gif',         name: 'doctor',		label: 'Doctor'		},
		{ url: 'data/img/signs/door.gif',         	name: 'door',		label: 'Door'		},
		{ url: 'data/img/signs/elephant.gif',       name: 'elephant',	label: 'Elephant'	},
		{ url: 'data/img/signs/email.gif',       	name: 'email',		label: 'Email'		},
		{ url: 'data/img/signs/false.gif',       	name: 'false',		label: 'False'		},
		{ url: 'data/img/signs/find.gif',       	name: 'find',		label: 'Find'		},
		{ url: 'data/img/signs/follow.gif',       	name: 'follow',		label: 'Follow'		},
		{ url: 'data/img/signs/garage.gif',       	name: 'garage',		label: 'Garage'		},
		{ url: 'data/img/signs/gomakeyourbed.gif',  name: 'gomakeyourbed',	label: 'Go Make Your Bed'	},
		{ url: 'data/img/signs/hike.gif',       	name: 'hike',		label: 'Hike'	},
		{ url: 'data/img/signs/holiday.gif',       	name: 'holiday',	label: 'Holiday'	},
		{ url: 'data/img/signs/icecream.gif',       name: 'icecream',	label: 'Ice Cream'	},
		{ url: 'data/img/signs/on.gif',             name: 'on', 		label: 'On'			},
		{ url: 'data/img/signs/own.gif',            name: 'own', 		label: 'Own'		},
		{ url: 'data/img/signs/pet.gif',            name: 'pet', 		label: 'Pet'		},
		{ url: 'data/img/signs/picture.gif',        name: 'picture', 	label: 'Picture'	},
		{ url: 'data/img/signs/play.gif',           name: 'play', 		label: 'Play'		},
		{ url: 'data/img/signs/police.gif',         name: 'police', 	label: 'Police'		},
		{ url: 'data/img/signs/president.gif',      name: 'president', 	label: 'President'	},
		{ url: 'data/img/signs/program.gif',        name: 'program', 	label: 'Program'	},
		{ url: 'data/img/signs/progress.gif',       name: 'progress',	label: 'Progress'	},
		{ url: 'data/img/signs/put-away.gif',       name: 'put-away',	label: 'Put Away'	},
		{ url: 'data/img/signs/rude.gif',       	name: 'rude',		label: 'Rude'		},
		{ url: 'data/img/signs/shirt.gif',       	name: 'shirt',		label: 'Shirt'		},
		{ url: 'data/img/signs/shower.gif',         name: 'shower', 	label: 'Shower'		},
		{ url: 'data/img/signs/singer.gif',         name: 'singer', 	label: 'Singer'		},
		{ url: 'data/img/signs/signlanguage.gif',   name: 'signlanguage', label: 'Sign Language'},
		{ url: 'data/img/signs/sit.gif',            name: 'sit', 		label: 'Sit'		},
		{ url: 'data/img/signs/sorry.gif',          name: 'sorry', 		label: 'Sorry'		},
		{ url: 'data/img/signs/speak.gif',          name: 'speak',		label: 'Speak'		},
		{ url: 'data/img/signs/stay.gif',           name: 'stay',		label: 'Stay'		},
		{ url: 'data/img/signs/steal.gif',          name: 'steal',		label: 'Steal'		},
		{ url: 'data/img/signs/step.gif',           name: 'step', 		label: 'Step'		},
		{ url: 'data/img/signs/table.gif',          name: 'table',		label: 'Table'		},
		{ url: 'data/img/signs/take.gif',           name: 'take', 		label: 'Take'		},
		{ url: 'data/img/signs/takecareof.gif',     name: 'takecareof', label: 'Take care of'},
		{ url: 'data/img/signs/tree.gif',           name: 'tree',		label: 'Tree'		},
		{ url: 'data/img/signs/wake-up.gif',        name: 'wake-up',	label: 'Wake Up'	},
		{ url: 'data/img/signs/walk.gif',        	name: 'walk',		label: 'Walk'		},
		{ url: 'data/img/signs/yes.gif',        	name: 'yes',		label: 'Yes'		},
	];

	return gifs;
});
